' (c) Crown copyright 2023 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

'==========================================
abstract class keyvalue_mod::keyvalue_type {
'==========================================
  -key: string <<kind=:, allocatable>>

  +initialise => keyvalue_initialise( <<in>>key:string<<kind=*>> )
  +get_key => get_keyvalue_key(): string<<kind=:,allocatable>>
}

'==========================================
class keyvalue_mod::i32_keyvalue_type {
'==========================================
  +value: integer <<kind=int32>>
  +initialise => init_i32_keyvalue(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:integer<<kind=int32>> )

  +get_key( ... )
}

'==========================================
class keyvalue_mod::i64_keyvalue_type {
'==========================================
  +value: integer <<kind=int64>>
  +initialise => init_i64_keyvalue(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:integer<<kind=int64>> )

  +get_key( ... )
}

'==========================================
class keyvalue_mod::r32_keyvalue_type {
'==========================================
  +value: real <<kind=real32>>
  +initialise => init_r32_keyvalue(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:real<<kind=real32>> )

  +get_key( ... )
}

'==========================================
class keyvalue_mod::r64_keyvalue_type {
'==========================================
  +value: real <<kind=real64>>
  +initialise => init_r64_keyvalue(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:real<<kind=real64>> )

  +get_key( ... )
}

'==========================================
class keyvalue_mod::logic_keyvalue_type {
'==========================================
  +value: logical
  +initialise => init_logic_keyvalue(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:logical )

  +get_key( ... )
}

'==========================================
class keyvalue_mod::str_keyvalue_type {
'==========================================
  +value: string
  +initialise => init_str_keyvalue(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:string<<kind=*>> )
 
  +get_key( ... )
}

'==========================================
class keyvalue_mod::i32_arr_keyvalue_type {
'==========================================
  +value: integer[:] <<kind=int32, allocatable>>
  +initialise => init_i32_arr_keyvalue(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:integer[:]<<kind=int32>> )

  +get_key( ... )
}

'==========================================
class keyvalue_mod::i64_arr_keyvalue_type {
'==========================================
  +value: integer[:] <<kind=int64, allocatable>>
  +initialise => init_i64_arr_keyvalue(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:integer[:]<<kind=int64>> )
 
  +get_key( ... )
}

'==========================================
class keyvalue_mod::r32_arr_keyvalue_type {
'==========================================
  +value: real[:] <<kind=real32, allocatable>>
  +initialise => init_r32_arr_keyvalue(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:real[:]<<kind=real32>> )

  +get_key( ... )
}

'==========================================
class keyvalue_mod::r64_arr_keyvalue_type {
'==========================================
  +value: real[:] <<kind=real64, allocatable>>
  +initialise => init_r64_arr_keyvalue(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:real[:]<<kind=real64>> )

  +get_key( ... )
}

'==========================================
class keyvalue_mod::logic_arr_keyvalue_type {
'==========================================
  +value: logical[:] <<allocatable>>
  +initialise => init_logic_arr_keyvalue(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:logical[:] )

  +get_key( ... )
}

'==========================================
class keyvalue_mod::str_arr_keyvalue_type {
'==========================================
  +value: string[:]<<kind=str_longlong,allocatable>>
  +initialise => init_str_arr_keyvalue(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:string[:]<<kind=*>> )

  +get_key( ... )
}


linked_list_data_mod::linked_list_data_type <|-- keyvalue_mod::keyvalue_type

keyvalue_mod::keyvalue_type <|-- keyvalue_mod::i32_keyvalue_type
keyvalue_mod::keyvalue_type <|-- keyvalue_mod::i64_keyvalue_type
keyvalue_mod::keyvalue_type <|-- keyvalue_mod::r32_keyvalue_type
keyvalue_mod::keyvalue_type <|-- keyvalue_mod::r64_keyvalue_type
keyvalue_mod::keyvalue_type <|-- keyvalue_mod::str_keyvalue_type
keyvalue_mod::keyvalue_type <|-- keyvalue_mod::logic_keyvalue_type

keyvalue_mod::keyvalue_type <|-- keyvalue_mod::i32_arr_keyvalue_type
keyvalue_mod::keyvalue_type <|-- keyvalue_mod::i64_arr_keyvalue_type
keyvalue_mod::keyvalue_type <|-- keyvalue_mod::r32_arr_keyvalue_type
keyvalue_mod::keyvalue_type <|-- keyvalue_mod::r64_arr_keyvalue_type
keyvalue_mod::keyvalue_type <|-- keyvalue_mod::str_arr_keyvalue_type
keyvalue_mod::keyvalue_type <|-- keyvalue_mod::logic_arr_keyvalue_type
