' (c) Crown copyright 2023 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

'==========================================
class namelist_item_mod::namelist_item_type {
'==========================================
  -key_value_pair: key_value_type <<allocatable>>

  +get_key(): string <<allocatable>>

  +generic :: initialise() => \n\tinit_int32, init_int64,\n\tinit_int32_arr, init_int64_arr,\n\tinit_real32, init_real64,\n\tinit_real32_arr, init_real64_arr,\n\tinit_logical, init_logical_arr,\n\tinit_str, init_str_arr

  +generic :: get_value() => \n\tvalue_int32, value_int64,\n\tvalue_int32_arr, value_int64_arr,\n\tvalue_real32, value_real64,\n\tvalue_real32_arr, value_real64_arr,\n\tvalue_logical, value_logical_arr,\n\tvalue_str, value_str_arr

  -init_int32( <<in>>key:string<<len=*>>, <<in>>value:integer<<kind=int32>> )
  -init_int64( <<in>>key:string<<len=*>>, <<in>>value:integer<<kind=int64>> )
  -init_real32( <<in>>key:string<<len=*>>, <<in>>value:real<<kind=real32>> )
  -init_real64( <<in>>key:string<<len=*>>, <<in>>value:real<<kind=real64>> )
  -init_logical( <<in>>key:string<<len=*>>, <<in>>value:logical )
  -init_str( <<in>>key:string<<len=*>>, <<in>>value:string<<len=*>> )
  -init_real32_arr( <<in>>key:string<<len=*>>, <<in>>value:real[:]<<kind=real32>> )
  -init_real64_arr( <<in>>key:string<<len=*>>, <<in>>value:real[:]<<kind=real64>> )
  -init_int32_arr( <<in>>key:string<<len=*>>, <<in>>value:integer[:]<<kind=int32>> )
  -init_int64_arr( <<in>>key:string<<len=*>>, <<in>>value:integer[:]<<kind=int64>> )
  -init_logical_arr( <<in>>key:string<<len=*>>, <<in>>value:logical[:] )
  -init_str_arr( <<in>>key:string<<len=*>>, <<in>>value:string[:]<<len=*>> )

  -value_int32( <<out>>value:integer<<kind=int32>> )
  -value_int64( <<out>>value:integer<<kind=int64>> )
  -value_real32( <<out>>value:real<<kind=real32>> )
  -value_real64( <<out>>value:real<<kind=real32>> )
  -value_logical( <<out>>value:logical )
  -value_str( <<out>>value:string<<len=*>> )
  -value_int32_arr( <<out>>value:integer[:]<<kind=int32, allocatable>> )
  -value_int64_arr( <<out>>value:integer[:]<<kind=int64, allocatable>> )
  -value_real32_arr( <<out>>value:real[:]<<kind=real32, allocatable>> )
  -value_real64_arr( <<out>>value:real[:]<<kind=int64, allocatable>> )
  -value_logical_arr( <<out>>value:logical[:]<<allocatable>> )
  -value_str_arr( <<out>>value:string[:]<<len=*,allocatable>> )
}
