' (c) Crown copyright 2023 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

'==========================================
class namelist_mod::namelist_type {
'==========================================
  -listname: string <<allocatable>>
  -profile_name: string
  -members: namelist_item_type[:] <<allocatable>>

  +initialise => namelist_initialise( \n\t<<in>>listname:string<<len=*>>, \n\t<<in>>members:namelist_item_type[:], \n\t<<in,optional>>profile_name:string<<len=*>> )

  +generic:: get_value() => \n\tget_i32_value, get_i32_arr_value,\n\tget_i64_value, get_i64_arr_value,\n\tget_r32_value, get_r32_arr_value,\n\tget_r64_value, get_r64_arr_value,\n\tget_logic_value, get_logic_arr_value,\n\tget_str_value, get_str_arr_value

  +get_listname():     string <<allocatable>>
  +get_profile_name(): string <<allocatable>>
  +get_full_name():    string <<allocatable>>

  +clear()
  +<<destroy>> namelist_destructor()

  -get_i32_value(   <<in>>key:string<<len=*>>, <<out>>value:integer <<kind=int32>> )
  -get_i64_value(   <<in>>key:string<<len=*>>, <<out>>value:integer <<kind=int64>> )
  -get_r32_value(   <<in>>key:string<<len=*>>, <<out>>value:real    <<kind=real32>> )
  -get_r64_value(   <<in>>key:string<<len=*>>, <<out>>value:real    <<kind=real64>> )
  -get_str_value(   <<in>>key:string<<len=*>>, <<out>>value:string  <<len=*>> )
  -get_logic_value( <<in>>key:string<<len=*>>, <<out>>value:logical )


  -get_i32_arr_value(   <<in>>key:string<<len=*>>, <<out>>value:integer[:] <<kind=int32,allocatable>> )
  -get_i64_arr_value(   <<in>>key:string<<len=*>>, <<out>>value:integer[:] <<kind=int64,allocatable>> )
  -get_r32_arr_value(   <<in>>key:string<<len=*>>, <<out>>value:real[:]    <<kind=real32,allocatable>> )
  -get_r64_arr_value(   <<in>>key:string<<len=*>>, <<out>>value:real[:]    <<kind=real64,allocatable>> )
  -get_str_arr_value(   <<in>>key:string<<len=*>>, <<out>>value:string[:]  <<len=*,allocatable>> )
  -get_logic_arr_value( <<in>>key:string<<len=*>>, <<out>>value:logical[:] <<allocatable>> )
}

linked_list_data_mod::linked_list_data_type <|-- namelist_mod::namelist_type
