' (c) Crown copyright 2023 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

'==========================================
abstract class key_value_mod::key_value_type {
'==========================================
  -key: string <<kind=:, allocatable>>

  +initialise => key_value_initialise( <<in>>key:string<<kind=*>> )
  +get_key => get_key_value_key(): string<<kind=:,allocatable>>
}

'==========================================
class key_value_mod::int32_key_value_type {
'==========================================
  +value: integer <<kind=int32>>
  +initialise => init_int32_key_value(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:integer<<kind=int32>> )
}

'==========================================
class key_value_mod::int64_key_value_type {
'==========================================
  +value: integer <<kind=int64>>
  +initialise => init_int64_key_value(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:integer<<kind=int64>> )
}

'==========================================
class key_value_mod::real32_key_value_type {
'==========================================
  +value: real <<kind=real32>>
  +initialise => init_real32_key_value(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:real<<kind=real32>> )
}

'==========================================
class key_value_mod::real64_key_value_type {
'==========================================
  +value: real <<kind=real64>>
  +initialise => init_real64_key_value(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:real<<kind=real64>> )
}

'==========================================
class key_value_mod::logical_key_value_type {
'==========================================
  +value: logical
  +initialise => init_logical_key_value(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:logical )
}

'==========================================
class key_value_mod::str_key_value_type {
'==========================================
  +value: string
  +initialise => init_str_key_value(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:string<<kind=*>> )
}

'==========================================
class key_value_mod::int32_arr_key_value_type {
'==========================================
  +value: integer[:] <<kind=int32, allocatable>>
  +initialise => init_int32_arr_key_value(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:integer[:]<<kind=int32>> )
}

'==========================================
class key_value_mod::int64_arr_key_value_type {
'==========================================
  +value: integer[:] <<kind=int64, allocatable>>
  +initialise => init_int64_arr_key_value(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:integer[:]<<kind=int64>> )
}

'==========================================
class key_value_mod::real32_arr_key_value_type {
'==========================================
  +value: real[:] <<kind=real32, allocatable>>
  +initialise => init_real32_arr_key_value(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:real[:]<<kind=real32>> )
}

'==========================================
class key_value_mod::real64_arr_key_value_type {
'==========================================
  +value: real[:] <<kind=real64, allocatable>>
  +initialise => init_real64_arr_key_value(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:real[:]<<kind=real64>> )
}

'==========================================
class key_value_mod::logical_arr_key_value_type {
'==========================================
  +value: logical[:] <<allocatable>>
  +initialise => init_logical_arr_key_value(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:logical[:] )
}

'==========================================
class key_value_mod::str_arr_key_value_type {
'==========================================
  +value: string[:]<<kind=str_longlong,allocatable>>
  +initialise => init_str_arr_key_value(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:string[:]<<kind=*>> )
}

'==========================================
class key_value_mod::abstract_key_value_type {
'==========================================
  +value: abstract_value_type[:]<<abstract,allocatable>>
  +initialise => init_abstract_key_value(\n\t<<in>>key:string<<kind=*>>,\n\t<<in>>value:abstract_value_type<<Abstract>> )
}


linked_list_data_mod::linked_list_data_type <|-- key_value_mod::key_value_type

key_value_mod::key_value_type <|-- key_value_mod::int32_key_value_type
key_value_mod::key_value_type <|-- key_value_mod::int64_key_value_type
key_value_mod::key_value_type <|-- key_value_mod::real32_key_value_type
key_value_mod::key_value_type <|-- key_value_mod::real64_key_value_type
key_value_mod::key_value_type <|-- key_value_mod::str_key_value_type
key_value_mod::key_value_type <|-- key_value_mod::logical_key_value_type

key_value_mod::key_value_type <|-- key_value_mod::int32_arr_key_value_type
key_value_mod::key_value_type <|-- key_value_mod::int64_arr_key_value_type
key_value_mod::key_value_type <|-- key_value_mod::real32_arr_key_value_type
key_value_mod::key_value_type <|-- key_value_mod::real64_arr_key_value_type
key_value_mod::key_value_type <|-- key_value_mod::str_arr_key_value_type
key_value_mod::key_value_type <|-- key_value_mod::logical_arr_key_value_type
key_value_mod::key_value_type <|-- key_value_mod::abstract_key_value_type
