' (c) Crown copyright 2023 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

class key_value_collection_mod::key_value_collection_type {
  -key_value_list: linked_list_type
  -name: string
  -table_len: integer

  +initialise(<<in optional>> name : string, <<in optional>> table_len : integer ) :
  +add_key_value( <<in>>key_value: key_value_type ) :
  +key_value_exists( <<in>>key: string ) :
  +remove_key_value( <<in>>key: string ) :
  +generic :: get_value() => \n\tget_int32_value, get_int64_value, \n\tget_real32_value, get_real64_value, \n\tget_logical_value, get_string_value, \n\tget_int32_arr_value, get_int64_arr_value, \n\tget_real32_arr_value, get_real64_arr_value, \n\tget_logical_arr_value, get_string_arr_value
  +get_length(): integer
  +get_name() : string
  +get_table_length(): integer
  -get_hash(<<in>>key:string<<len=*>>) : integer
  +clear() :
  <<destroy>>+key_value_collection_destructor()

  -get_int32_value(   <<in>>key:string<<len=*>>, <<out>>value:integer <<kind=int32, pointer>> )
  -get_int64_value(   <<in>>key:string<<len=*>>, <<out>>value:integer <<kind=int64, pointer>> )
  -get_real32_value(   <<in>>key:string<<len=*>>, <<out>>value:real    <<kind=real32, pointer>> )
  -get_real64_value(   <<in>>key:string<<len=*>>, <<out>>value:real    <<kind=real64, pointer>> )
  -get_str_value(   <<in>>key:string<<len=*>>, <<out>>value:string  <<len=*, pointer>> )
  -get_logical_value( <<in>>key:string<<len=*>>, <<out>>value:logical <<pointer>> )
  -get_int32_arr_value(   <<in>>key:string<<len=*>>, <<out>>value:integer[:] <<kind=int32, pointer>>)
  -get_int64_arr_value(   <<in>>key:string<<len=*>>, <<out>>value:integer[:] <<kind=int64, pointer>> )
  -get_real32_arr_value(   <<in>>key:string<<len=*>>, <<out>>value:real[:]    <<kind=real32, pointer>> )
  -get_real64_arr_value(   <<in>>key:string<<len=*>>, <<out>>value:real[:]    <<kind=real64, pointer>> )
  -get_str_arr_value(   <<in>>key:string<<len=*>>, <<out>>value:string[:]  <<len=*, pointer>> )
  -get_logical_arr_value( <<in>>key:string<<len=*>>, <<out>>value:logical[:] <<pointer>> )
  -get_abstract_value(   <<in>>key:string<<len=*>>, <<out>>value:abstract_value_type <<abstract, pointer>> )
}
